### ISSUE TITLE
Why? What? Who? How?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/vinyl-record-carry-storage-box#1]
# _Context_ 🤦‍♂️ 

> I have a _modest_ collection (~100) of vinyl records.
The ones I couldn't bring myself to sell/give away when I sold my decks before Uni.
They are safely stored on a shelf in the (MDC) garage.
This mini-project is not for me. It's for a friend ... ⬇️ 
But if this project is successful, I will make a couple of boxes for myself too. 💭 
They will be good (secure) long-term storage for my disks and will allow me to _safely_ transport them back from UK -> PT.

## _Thousands_ Of Records to Store/Transport

A **DJ friend** who has **several _thousand_ vinyl records**, 
stores/transports them to gigs in _cardboard_ (_free_) **fruit boxes** in the back of their van ...
Not only is this _risky_, considering the average price of a record is **`$20`** 
(_some his records are **collectable/vintage** and are worth **$100's** per disk!!_), 
it also **_looks_ bad** for a Pro DJ to be carting around tatty cardboard boxes.

### `$1k/box`!! 💸 

If we estimate that each box has **50 records** in it, 
and the  average price of each record is a _conservative_ **`$20`**;
that's a ***grand*** (**`$1000`**) per box!! 💰 

Did I mention that he has around **80** of these fruit boxes? 📦 
(_he has lost count of them and has no system for organising them either ...!_)
and it takes up most of a 4 car garage at his family home...? 🙄 

> Take a moment to pause and consider that this person has a _lifetime_ worth of collecting music,
_easily_ more than **`$50k`** of vinyl records stored in cardboard boxes ... 🤯 
It borders on "**hoarding**" ... except that records are a fairly "liquid" (easily saleable)
and appreciating asset (if well looked after ...!)

The records are not well stored in these fruit boxes and could easily be damaged. 

I'd wager that there are at least 1k (_amateur_) DJs with decent record collections 
who are in a similar situation. Perhaps not this bad ...

## Fruit Boxes with Vinyl Don't Stack Well ...

The fruit boxes are stackable with _fruit_ in them, 
but the density of vinyl is _much_ higher than bananas,
so when he offloads them from his van they are mostly spread across the garage floor
which takes up a _ridiculous_ surface area.

# Todo

+ [x] Research available vinyl storage boxes!
+ [x] Figure out the dimensions required
+ [x] Design a _system_!
  + [x] Target Material: 10mm plywood
  + [x] Sturdy 
  + [x] Lightweight
  + [x] Handles
  + [x] Stackable when stored on level ground (_not for transporting!_)
  + [x] _Optional_: Integrated lid for minimising dust
+ [x] Create a prototype in LightBurn
+ [x] Cut on Laser

**Comment by nelsonic** [comment]
Google Search: vinyl record carry case wood
https://www.google.com/search?q=vinyl+record+carry+case+wood&tbm=isch
![image](https://user-images.githubusercontent.com/194400/167263835-9c5e0c4a-81a1-4fdb-8704-b2dd5a855daf.png)

**Comment by nelsonic** [comment]
https://www.etsy.com/market/wood_record_box
![image](https://user-images.githubusercontent.com/194400/167263877-df91cac1-aa99-4161-8ba2-06fdf88a9589.png)

https://www.etsy.com/listing/1039809833/record-storage-crate-vinyl-record
![image](https://user-images.githubusercontent.com/194400/167263906-78a71db2-9f65-4545-8f33-666e7b5f86fc.png)

**Comment by nelsonic** [comment]
First Draft of a storage box for 7" Singles (the smallest type of vinyl record) in LightBurn:

![image](https://user-images.githubusercontent.com/194400/167275455-ac2f83f4-3f52-4281-8fb2-20467730e916.png)

Making the first few prototypes for the 7" SPs as it doesn't waste as much material (plywood) if I make design mistakes.
See: https://vinyl-waller.fr/blogs/blog-disque-vinyl/formats-de-vinyles-guide-pratique-pour-comprendre-les-formats-vinyles?ls=en for more detail on record sizes.

**Comment by nelsonic** [comment]
It's too late to be operating the laser tonight. But we can fire it up and laser-cut the prototype tomorrow. 🤞

**Comment by nelsonic** [comment]
Turned the layout through 90* so it's "landscape":

![image](https://user-images.githubusercontent.com/194400/167275920-2e78097e-60b6-4fc9-8141-0ca4a388443b.png)

If it's unclear how these pieces go together, don't worry, it will be clear once they are assembled.

**Comment by nelsonic** [comment]
Put the design to laser cut this evening:
![8756F484-01A3-439E-A0A3-8F9FC6A704EF](https://user-images.githubusercontent.com/194400/167316250-d55e8fe3-2246-4023-984b-da34255d8b18.jpeg)

supervised the machine during the cut.
But next time could just leave it running as I know how it will turn out. 👌🏻

Assembled and glued the pieces:

![785F0E9E-6B33-449B-9E33-38658BF6F30B](https://user-images.githubusercontent.com/194400/167316275-33e11a46-d0ef-4d63-b2ee-fb3b3b11fae9.jpeg)

integrated lid/hinge mechanism works well:

![8938A512-E58B-4CD1-8FA0-272D0B5AE250](https://user-images.githubusercontent.com/194400/167316374-9cea4b21-44e2-4eb4-87b4-503f147276c0.jpeg)

the lid disappears into the back:
![24F6A23A-CAEE-4E0A-B943-EAE3D68D1416](https://user-images.githubusercontent.com/194400/167316411-10861770-1f8a-4f71-a00f-cacdf35e23cf.jpeg)

Handles are ergonomic/comfortable:
![3A9DBBFA-120C-49BF-AB00-C6D715496795](https://user-images.githubusercontent.com/194400/167316424-3c0be9f5-1374-4746-9b84-87774cf7410a.jpeg)

Overall I think it’s decent for a first prototype.
It can easily store ~50 x 7” Singles.
The design is sturdy and practical.
Will get feedback from my DJ friend tomorrow. ⏳

**Comment by nelsonic** [comment]
Oh, yeah in case you’re wondering, his name is “Miguel Antunes” (like “Michael” in Portuguese).
I couldn’t help myself, had to emphasise the fact that his name has the word “Tunes” in it!

he doesn’t emphasise it at all. This is his logo:

![96AA18B6-641E-4A85-B05C-BAFB23461742](https://user-images.githubusercontent.com/194400/167316568-ff17b3e3-acc9-4875-b2d9-57ce6b0c2a12.jpeg)

I was tempted to try and import his branding and try to make it work in laser … but really just wanted to focus on building the prototype for this iteration.

**Comment by nelsonic** [comment]
Here’s an interesting infographic;

![D8FC46F0-93E8-418F-8006-01E3EC020363](https://user-images.githubusercontent.com/194400/167316783-89d1332b-fa82-45ee-908c-dc3deb915243.png)

via: https://vinylrestart.com/vinyl-records-revival-data-and-infographic/

**Comment by nelsonic** [comment]
Basically vinyl sales are growing gangbusters!
For instance @iteles’s cousin Luis @LuchoTurtle is in his mid 20’s and listens to his favourite tunes on Vinyl. Same with our friend @th0mas, early 20’s, buys vinyl. It’s not just “old” people buying them out of nostalgia… 😜

**Comment by LuchoTurtle** [comment]
This is amazing, holy mother of god 🤩🤩.
Curious if there are plans for 12'' LPs 👀

**Comment by nelsonic** [comment]
Yo @LuchoTurtle, definitely! Will be making a 12” version very soon. Still have to iron out some kinks in the design before scaling up. ⚡️
this was just the “first draft” I made to have something physical to work off. I’ve already spotted several areas for improvement/enhancement. 
Need to work on bottom of the box for making them stackable. 

But definitely; 12” is where the vast majority of Vinyl is. 👌🏻

**Comment by nelsonic** [comment]
https://www.hhv.de/shop/en/storage/p:Q0G2fb
![image](https://user-images.githubusercontent.com/194400/167369389-b9ca1ffb-5f0b-4d3a-b026-8057ce622392.png)

https://www.hhv.de/shop/en/item/musicbox-designs-lp-storage-box-65-natural-oak-580131
![image](https://user-images.githubusercontent.com/194400/167369504-5be8df0f-a5ab-4fd2-915d-de8c845588a2.png)

**Comment by nelsonic** [comment]
Miguel (DJ friend) confirmed that the box fits 50 x 7” SP records:

![7986AD95-45F2-446B-B501-F0E1090B7C81](https://user-images.githubusercontent.com/194400/167490594-e4fd2597-d727-459e-8e49-878d3a6b34bc.jpeg)

he liked the prototype.
I know what to do next:
1. make the lid shorter so it folds away better and 2. try and create the “front cover” index holder (I didn’t have the energy to design on Saturday night when I was designing the V1) 
2. add the “tracks” the base to make them stackable.
3. Change the handles so they are rectangular

**Comment by nelsonic** [comment]
V2 layout:
![image](https://user-images.githubusercontent.com/194400/168929951-e73f1178-e21f-456e-a8ff-ac15fc9bc5d0.png)

**Comment by nelsonic** [comment]
3 instances of the design fit perfectly on a 1200 x 600 sheet of plywood:

![image](https://user-images.githubusercontent.com/194400/168930287-c534b41e-f5d1-48f1-8979-4a42b5aaa94e.png)

My plan is to laser cut them tomorrow during my lunch break.
And assemble two of them in the evening.

**Comment by nelsonic** [comment]
The design has a number of improvements:
1. improves the strength of the hinges by doubling the material around them.
2. adds a front-cover that folds down and tucks 
3. simplifies handles (holes) with consistent proportions
4. lid "locks" in place with the front-cover
5. adds "tracks" to the base so the boxes stack well.
6. uses less material than the previous design
7. should require less time to assemble and be easier to use.

**Comment by nelsonic** [comment]
v3 design:
![image](https://user-images.githubusercontent.com/194400/169662421-dc26c5ac-8653-4300-a4a7-2e8d7ce24f94.png)

**Comment by nelsonic** [comment]
The v3 (7" single) design turned out very well. (photos to follow)

v4 design: (12" disks)
![image](https://user-images.githubusercontent.com/194400/169672342-88173065-e7c7-4864-bfba-1dca53b1bc3b.png)

**Comment by RafaJPSantos** [comment]
Luis wasn't joking around, these are great! I'd love to get one for my LP collection ⛷️

**Comment by nelsonic** [comment]
Yo @RafaJPSantos! I haven't even uploaded the V4 pictures. Thanks for the reminder. 😉 

![image](https://user-images.githubusercontent.com/194400/173869016-207a8d17-6624-4253-9228-6846245a1688.png)

![image](https://user-images.githubusercontent.com/194400/173869047-015738e6-2063-40c4-8fc4-7cdbd21c3c53.png)

![image](https://user-images.githubusercontent.com/194400/173869213-5a2d1f71-dee7-4da5-a916-6400a0a17ea2.png)

![image](https://user-images.githubusercontent.com/194400/173870437-24f30068-a102-49aa-baa9-5ed22a33fda8.png)

Note this is "unfinished" plywood ... Our friend (DJ Miguel Antunes) wants them to be painted [matte black](https://mkbhd.com/products/matte-black-everything-t-shirt) with fluorescent yellow accents so they "pop" under UV light in the club. 🕺 😎 

The idea of the fold-down front is that it has the list of the LPs in the box in the order they are stored
so that it's easy to find an album/track quickly. 🔍 

You're very welcome to come and cut+assemble your own cases if you want to. 📦 
@LuchoTurtle knows where we live. just come with him some time. 👌 
You can learn how to use LightBurn in 5 mins and personalise the cases. 🖥️ 
And if you don't _already_ know how to use a laser-cutter, you can learn that too; it's easy! ***pew-pew***! ⚡ 

The laser-cutting takes around 30 mins because of the logo etching etc. ⏳ 
But assembly takes 5 mins and we have any color of paint or varnish you like in our workshop. 🎨 
Aparece! 😉

**Comment by nelsonic** [comment]
First 3 prototypes side-by-side:
![F90B101A-400C-49DF-9647-800EF5E97514](https://user-images.githubusercontent.com/194400/175216853-5cda0d2c-8805-4cdb-8f4b-a32b998d70ef.jpeg)

**Comment by nelsonic** [comment]
New logo:

![2D5D4B7B-5360-4CA0-B122-A1E0EF8FDE52](https://user-images.githubusercontent.com/194400/197245368-ae684aeb-1611-4329-9af5-261828a5401d.jpeg)

**Comment by nelsonic** [comment]
www.djmiguelantunes.pt

**Comment by nelsonic** [comment]
Sneak peak of v6 box
![6B4F113C-3FB5-4368-B57A-1DCF63D0B463](https://user-images.githubusercontent.com/194400/197591243-d96c908a-bd98-4e4f-b35e-3192762ac1c2.jpeg)

with giant QR code that links to his (still in progress) website:

![8031792A-F251-4608-8CC2-E079CDA66225](https://user-images.githubusercontent.com/194400/197591356-29579c67-68bb-4635-8e3d-4d553b2612a4.png)

**Comment by nelsonic** [comment]
Video featuring the vinyl storage/transport box in-use:  https://www.youtube.com/watch?v=p1CdZusD7Xk

![661202AB-15A7-42EE-A529-6E8C07383153](https://user-images.githubusercontent.com/194400/202850227-d011eea0-9374-4cef-8f0f-d7aa841773c3.png)

**Comment by nelsonic** [comment]
@LuchoTurtle please upload the photos you took of the most recent vinyl box. 🙏

**Comment by LuchoTurtle** [comment]
There ya go! It was a breeze to put everything together (at `6` speed and `80% power` seems to be ideal for 10mm plywood).

![410830232_3429077830646302_308730173852476286_n](https://github.com/nelsonic/vinyl-record-carry-storage-box/assets/17494745/e073eeaa-d25a-4e0f-80bf-11734b919bd1)
![411061423_912065973401460_4075446876617069952_n](https://github.com/nelsonic/vinyl-record-carry-storage-box/assets/17494745/4f3d5f04-6606-4ad6-8b30-3e4f2f149d8b)

**Comment by nelsonic** [comment]
Nice! Thanks for uploading! Hope Antonio liked his box. 📦👌
